name: Nuclei - DAST Scan
permissions: read-all

on:
    schedule:
      - cron: '0 7 * * 1'
    workflow_dispatch:

jobs:
  nuclei-scan:
    name: nuclei-scan
    permissions:
        security-events: write
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Nuclei - DAST Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://kidsloop.net
          user-agent: "User-Agent:'Sam GitHub Actions Nuclei Test'"

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: nuclei.sarif
