name: Test
on:
  push:
    branches: [main]

jobs:
  first-job:
    runs-on: ubuntu-latest  
    steps:
    
    - name: Create-output
      id: testing
      run: |
        echo "hello" >> test.out
        echo "::set-output name=output::$(cat test.out)"
        
    - name: print-output
      run: |
        echo "${{ steps.testing.output }}"
