name: Test
on:
  push:
    branches: [main]

jobs:
  first-job:
    runs-on: ubuntu-latest  
    steps:
    
    - name: Create-output
      id: testing
      run: |
        echo "hello" >> test.out
        echo "::set-output name=output::$(cat test.out)"
        echo $(cat test.out)
        
    - name: print-output
      run: |
        echo "${{ steps.testing.outputs.output }}"
        
    - name: Set the value
      id: step_one
      run: |
        echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
        curl https://httpbin.org/json >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo ${{ env.JSON_RESPONSE }}
